name: build-apk
run-name: ${{ github.actor }} is building an APK
on:
  push:
    branches:
      - 'master'
jobs:
  build-apk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g yarn eas-cli
      - run: yarn install
      - run: yarn android-apk
